workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-32
  replicaCount: 1
  diskSpec:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
  containerSpec:
    imageUri: gcr.io/qwiklabs-gcp-04-36e4c9313f35/isugan:cok
