workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-16
  replicaCount: 1
  diskSpec:
      bootDiskType: pd-ssd
      bootDiskSizeGb: 100
  containerSpec:
    imageUri: gcr.io/beaming-signal-463711-j6/edan:elu
